"""Change Value in Comment Table

Revision ID: abae9a134a84
Revises: 3c8c45e678c6
Create Date: 2017-11-04 23:17:52.670279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abae9a134a84'
down_revision = '3c8c45e678c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_email', table_name='comments')
    op.create_index(op.f('ix_comments_email'), 'comments', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_email'), table_name='comments')
    op.create_index('ix_comments_email', 'comments', ['email'], unique=True)
    # ### end Alembic commands ###
